let firstName = 'Moad';
let lastName = 'Mekki';
let country = 'Algeria';
let city = 'Oran';
let age = 18;
let isMarried = false;
console.log(typeof firstName); // string
console.log(typeof lastName); // string
console.log(typeof country); // string
console.log(typeof city); // string
console.log(typeof age); // number
console.log(typeof isMarried); // boolean
let year = 2026;
console.log(typeof year); // number 