const sentence = "Love is the best thing in this world. Some found their love and some are still looking for their love.";
const count = sentence.toLowerCase().split("love").length - 1;
console.log(count);
const string = 'You cannot end a sentence with because because because is a conjunction';
let pattern = /because/gi;
const becauseCounter = string.match(pattern).length;
console.log(becauseCounter);
let string2 = 'He earns 5000 euro from salary per month, 10000 euro annual bonus, 15000 euro online courses per month.';
const numbers = string2.match(/\d+/g);
console.log(numbers);
const annualIncome = Number(numbers[0]*12) + Number(numbers[1]) + Number(numbers[2]*12);
console.log(annualIncome + "Euros");
const txt = '%I $am@% a %tea@cher%, &and& I lo%#ve %te@a@ching%;. The@re $is no@th@ing; &as& mo@re rewarding as educa@ting &and& @emp%o@weri@ng peo@ple. ;I found tea@ching m%o@re interesting tha@n any ot#her %jo@bs. %Do@es thi%s mo@tiv#ate yo@u to be a tea@cher!? %Th#is 30#Days&OfJavaScript &is al@so $the $resu@lt of &love& of tea&ching';
const cleanTxt = txt.replace(/[^a-zA-Z\s]/g,'');
console.log(cleanTxt);